Repository AY2324S2-CS2103T-T14-2/tp, pull requests merged in 2024-04, with the labels that each got.

#69 Add appointment field in patient
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DateTimeParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/patient/Appointment.java
  src/main/java/seedu/address/model/patient/DateOfBirth.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/test/data/JsonPatientListStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializablePatientListTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializablePatientListTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPatientDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DateTimeParserTest.java
  src/test/java/seedu/address/logic/parser/PatientListParserTest.java
  src/test/java/seedu/address/model/patient/AppointmentTest.java
  src/test/java/seedu/address/model/patient/PatientTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/PatientUtil.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: type.Task, priority.High

#70 Add Visit model, update storage and ui
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/patient/Address.java
  src/main/java/seedu/address/model/patient/Condition.java
  src/main/java/seedu/address/model/patient/DateOfVisit.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/patient/Severity.java
  src/main/java/seedu/address/model/patient/SeverityOption.java
  src/main/java/seedu/address/model/patient/UniqueVisitList.java
  src/main/java/seedu/address/model/patient/Visit.java
  src/main/java/seedu/address/model/patient/exceptions/DuplicateVisitException.java
  src/main/java/seedu/address/model/patient/exceptions/VisitNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/storage/JsonAdaptedVisit.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/resources/view/PatientListCard.fxml
  src/test/data/JsonPatientListStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonPatientListStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializablePatientListTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializablePatientListTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializablePatientListTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/model/patient/PatientTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
Labels: type.Story, priority.High

#76 Change all mentions of 'person' to 'patient'
  src/test/data/JsonPatientListStorageTest/invalidAndValidPatientAddressBook.json
  src/test/data/JsonPatientListStorageTest/invalidPatientAddressBook.json
  src/test/data/JsonSerializablePatientListTest/duplicatePatientAddressBook.json
  src/test/data/JsonSerializablePatientListTest/invalidPatientAddressBook.json
  src/test/data/JsonSerializablePatientListTest/typicalPatientAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteByIndexCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteByIndexCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/PatientListParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/PatientListTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/storage/JsonPatientListStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializablePatientListTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/PatientUtil.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: type.Task, priority.High

#75 Add 'exit' and 'exit-f' for user to exit the program
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/ForceExitCommand.java
  src/main/java/seedu/address/logic/commands/YesCommand.java
  src/main/java/seedu/address/logic/parser/InputParser.java
  src/test/java/seedu/address/logic/commands/ForceExitCommandTest.java
  src/test/java/seedu/address/logic/parser/PatientListParserTest.java
Labels: type.Task, priority.High

#74 Add crud commands for visit
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddVisitCommand.java
  src/main/java/seedu/address/logic/commands/DeleteVisitCommand.java
  src/main/java/seedu/address/logic/commands/EditVisitCommand.java
  src/main/java/seedu/address/logic/parser/AddVisitCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteVisitCommandParser.java
  src/main/java/seedu/address/logic/parser/EditVisitCommandParser.java
  src/main/java/seedu/address/logic/parser/InputParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/PatientList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Epic, priority.High

#78 Add command for deleting a patient by name and phone number
  src/main/java/seedu/address/logic/commands/DeleteByNamePhoneNumberCommand.java
  src/main/java/seedu/address/logic/parser/DeleteByIndexCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteByNamePhoneNumberCommandParser.java
  src/main/java/seedu/address/logic/parser/InputParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/DeleteByIndexCommandParserTest.java
Labels: type.Task, priority.High

#83 Update UG, fix spelling issues
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/findAlexRoyResult.png
  src/main/java/seedu/address/logic/parser/DateTimeParser.java
Labels: type.Task, priority.High

#84 Update UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteByIndexCommand.java
  src/test/java/seedu/address/logic/commands/DeleteByIndexCommandTest.java
Labels: type.Task, priority.High

#85 Update UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListAlphabeticalCommand.java
  src/main/java/seedu/address/logic/commands/ListByApptDateCommand.java
  src/main/java/seedu/address/logic/commands/ListByDateCriteriaCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/InputParser.java
  src/main/java/seedu/address/logic/parser/ListByDateCriteriaCommandParser.java
  src/main/java/seedu/address/model/patient/ApptDateMatchesPredicate.java
Labels: type.Task, priority.High

#37 Modify validation of names and related tests
  src/main/java/seedu/address/model/patient/Name.java
  src/test/java/seedu/address/model/patient/NameTest.java
  src/test/java/seedu/address/model/patient/PatientTest.java
Labels: type.Bug, priority.Low

#89 Update UG Command Summary
  docs/UserGuide.md
Labels: type.Task, priority.High

#151 Update UG
  docs/UserGuide.md
Labels: type.Task, priority.High

#155 Resolve delete-p bug
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteByNamePhoneNumberCommand.java
  src/main/java/seedu/address/logic/parser/DeleteByNamePhoneNumberCommandParser.java
Labels: type.Bug, priority.High

#159 Update DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#161 Add error message for list-until-date
  src/main/java/seedu/address/logic/commands/ListByDateCriteriaCommand.java
  src/main/java/seedu/address/logic/parser/ListByDateCriteriaCommandParser.java
Labels: type.Bug

#164 Update AboutUS
  docs/AboutUs.md
Labels: type.Task, priority.High

#171 Update error and invalid inputs handling
  docs/UserGuide.md
Labels: type.Task, priority.High
