Repository AY2324S2-CS2103T-T14-2/tp, pull requests merged in 2024-03, with the labels that each got.

#14 Update AboutUs page
  docs/AboutUs.md
  docs/images/jeong-jaeho.png
Labels: type.Task, priority.High

#16 Update Aishvarya details in AboutUs page
  docs/AboutUs.md
  docs/images/s-aishvarya.png
Labels: type.Task, priority.High

#18 Update README.md
  README.md
Labels: type.Task, priority.High

#24 Update mentions and links to AB3
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug

#26 Add more roles
  docs/AboutUs.md
Labels: type.Task, priority.High

#39 Add delete-all and delete-all-f command
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAllCommand.java
  src/main/java/seedu/address/logic/commands/ForceDeleteAllCommand.java
  src/main/java/seedu/address/logic/commands/NoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ForceDeleteAllCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Story, priority.High

#42 Fix bug causing app to crash
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: type.Bug, priority.Medium

#47 Add DeleteByIndex class for deleting by selecting index
  src/main/java/seedu/address/logic/commands/DeleteByIndexCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteByIndexCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteByIndexCommandParserTest.java
Labels: type.Task, priority.High

#40 Add sex field to PersonCard
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Task, priority.High

#46 Fix bug with edit command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: type.Bug, priority.Medium, severity.Medium

#35 Modify Find command to work with phone numbers
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/patient/DateOfBirth.java
  src/main/java/seedu/address/model/patient/PhoneMatchesPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/patient/PhoneMatchesPredicateTest.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
Labels: type.Story, priority.Medium

#50 Update ListCommand
  src/main/java/seedu/address/logic/commands/ListCommand.java
Labels: type.Story, priority.High

#58 Update DG with Find implementation
  docs/DeveloperGuide.md
  docs/diagrams/FindActivityDiagram.puml
  src/main/java/seedu/address/MainApp.java
Labels: type.Task

#60 Update DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#59 Add List UML Sequence Diagram
  docs/diagrams/ListSequenceDiagram.puml
Labels: type.Task, priority.High

#62 Update DG with List in alphabetical order implementation
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#61 Enable assertions
  build.gradle
Labels: type.Task, priority.High

#41 Add CLI flags
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/Flag.java
Labels: type.Task
